feat(*): change blocking pr script

diff --git a/.github/workflows/post-push.yml b/.github/workflows/post-push.yml
--- a/.github/workflows/post-push.yml
+++ b/.github/workflows/post-push.yml
@@ -33,7 +33,6 @@ jobs:
                   echo "result<<EOF" >> $GITHUB_OUTPUT
                   echo "$OUTPUT" >> $GITHUB_OUTPUT
                   echo "EOF" >> $GITHUB_OUTPUT
-                  exit $EXIT_CODE
 
             # Проверка форматирования
             - name: Run format check
@@ -98,10 +97,11 @@ jobs:
 
             # Блокировка ПР при наличии ошибок линтера или ошибок форматирования
             - name: Block PR if checks failed
-              if: steps.lint.outcome != 'success' || steps.format.outcome != 'success'
               run: |
-                  echo "CI failed"
-                  exit 1
+                  if [ "${{ steps.lint.outputs.exit_code }}" != "0" ] || [ "${{ steps.format.outputs.exit_code }}" != "0" ]; then
+                    echo "CI failed"
+                    exit 1
+                  fi
 
             # Выпуск beta версии библиотеки, если в commit message есть вхождение строки "deploy_beta"
             - name: Publish beta version
